language: java
jdk:
- oraclejdk8
dist: trusty
install: true
deploy:
  provider: script
  script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
  skip_cleanup: true
env:
  global:
  - secure: NA7JPENyWLJiT6dNl5TA2WhwVBjab66PK/Nsh2Yzp7jv5wqz0FBMfhZpGcsdxhABrDhQbn5O2owKmyu1fNo33vqDdVSaRTr7dxqoT9OdotyazSfT9YP1aGJn4Fee5xQWSEzp6J1RlfIPht59P0jsYmJpcqUlXBBrLnQh8S6qNeBzS6JzWdpbIjGYv8egSGHsKMHErmgeIQvUuisNK3sZnd8Y9kjZocYuR4LBaMWsEpfy61fGG6mqL4vAVJ/s/xNhhyjItfE9dpH2ySy6gfJkkpIyStoPAyz69cOXWiCKSvIpX1xGe2AMKMoNYOem5KMhI6/Cnn7JeW8VEEG7J7qCl3GMTSB2rpW7+zvQNuSYtzbztAZ1b+pO+YHALhUralTTRxY8nI2UUcB7TIqlll/TZGBYF8Fro5HWRPeJ0HV/tJGmTXXcytsUPdhrfkCCDSvh9F7/kSNBBKwjgKMsULVVxU1P9dAD5NxJquiXe0JAEeioRtWU1JcnuxhT4z3fyR9+T68k7ZAIqXeipmISxt4zOFkwUkgNxTRKCQi+GhUCFACK7DUFziM0kajivoGxk7kk2ICmhxbqLgGDADMgbjTovsI516zRO40bjfcyEVfS/E5s13lgBW8RR4ospS6yvxV1DWE29PZPMNX4U2i+g/7jNp5sA+BpjUIR9pMqNTC11Lk=
  - secure: M6VBA7t0+hxd0wpHDlx0Lmji3N5NjRmjMpaksDCuF0uUbus/j0rouYIbAXIIDfL6xf6alrhiNM1O+4kXpP3uxlVDmQLn3Xf5zxVufSscEMyeP9Ad9GciYPBjjRbIr/zzjUO2HJV4zbpgYJliLXkzBRt9dhvgERfp3VRGFrpLS0qdcZAluRryQV8yR8qCA0MIeiGaeVVgGXs9Pvr1s6aK/2+JZRC5c2aN+QO0LBjHNqZsqhnaqRuSNfSXt/wDMlzRXvtD+ByQUohrxDgXLmw2iakJc59ydCPvkWh5v+/YBNHnMU9hB2StKC1Y5GEkopxTCiEkgmOBoyzwxViTNx9TZpiWPwUUEQRd/Wm70k69shZ69ClOMFfd5oUWRcwC2C3q3Fvetre9TFNWsB7IGln0uKVTjCByU6fIJmn+CVJ0L0kLW+u6uqKo376HZ92wFCKWfhZ+hSOsXsfpRKNWQ6ZTl/y7YKI/JA4NPjdFHoqyJtAScYkGBtKLhUG+z97ofXecDlKTWEKaGrBrjNNCA5ZGZ0L3830QwBNSFk4SJMYmZATqiHGoFEi89D2BKZdbm//brkE/g9/SjTWrLJYJyUSJodu8rE+ntw/7KQVgEFhl3wQmuFfF+pgogZh8Ol8gAgpY0Qv7PcxthdYlnln6BFWzsOR9y1ZATdpatzv46h4ZFB8=
